name: lock_screen
description: A way to lock user interaction during asynchronous operations
version: 1.0.0
homepage: https://github.com/epo33/lock_screen

publish_to: "none"

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=3.3.6"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
