name: lock_screen
description: A way to lock user interaction during asynchronous operations
version: 0.9.0
homepage: https://github.com/epo33/lock_screen

environment:
  sdk: ">=2.18.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  multi_listenable:
    path: ../multi_listenable

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
